app:
  name: "web-app"
  mode: "dev"
  port: 8080
  version: 1.0.0.1

log:
  level: "debug"
  filename: "web-app.log"
  max_size: 200
  max_backups: 7
  max_age: 7

mysql:
  host: "121.5.5.83"
  port: 3307
  user: "root"
  password: "Liuchang15050"
  db: "gin-template"
  max_open_conns: 20
  max_idle_conns: 10

redis:
  host: "121.5.5.83"
  port: 6379
  password: "Liuchang15050"
#  使用默认的数据库
  db: 0
  pool_size: 100

